### ISSUE TITLE
[gadget] phpdoc

### ISSUE THREAD

**Issue by DavidBadura** [simpspector/analyser#13]

**Comment by tolry** [comment]
Should this enforce doc blocks, even if none are necessary: e.g. all methods that don't have a return value and type hints on all arguments? :smile: 

Those edge cases aside, do you know a lib that would help us with this?

**Comment by DavidBadura** [comment]
> Should this enforce doc blocks, even if none are necessary

this should be configurable :wink: 

https://github.com/phpDocumentor/ReflectionDocBlock
https://github.com/mnapoli/PhpDocReader
