### ISSUE TITLE
.pdepend folder grew to 2.6 GB

### ISSUE THREAD

**Issue by tolry** [simpspector/analyser#14]
_From @DavidBadura on January 16, 2015 14:5_

related: https://github.com/phpmd/phpmd/issues/90

_Copied from original issue: simplethings/SimpSpector#91_

**Comment by tolry** [comment]
What would be our next action here? At least remove the file after computation?

**Comment by DavidBadura** [comment]
This issue should be fixed with commit https://github.com/pdepend/pdepend/commit/56712b10c78a17f8305436c5a4ccdf3106107691.
