### ISSUE TITLE
integrate phpmetrics

### ISSUE THREAD

**Issue by tolry** [simpspector/analyser#15]
_From @tolry on December 31, 2014 9:9_

This will probably not be a simple gadget as I am not really sure how to integrate this with our current architecture, but looks "really cool" :smile: 

sitepoint article http://www.sitepoint.com/visualize-codes-quality-phpmetrics/
homepage http://www.phpmetrics.org/
example http://www.phpmetrics.org/report/latest/index.html

thanks to th for the hint

_Copied from original issue: simplethings/SimpSpector#87_

**Comment by tolry** [comment]
@DavidBadura @larsborn @dragonito @smoench @DanielBadura 

A concept on how to integrate this might be a good topic for our next coding dojo!?

**Comment by tolry** [comment]
_From @larsborn on December 31, 2014 14:20_

+1

ot: happy new year!

**Comment by tolry** [comment]
_From @dragonito on January 5, 2015 10:22_

+1

**Comment by tolry** [comment]
_From @larsborn on February 8, 2015 17:58_

did we speak about this last time? Or should we do this tomorrow?

**Comment by tolry** [comment]
_From @DavidBadura on February 8, 2015 21:43_

tomorrow :wink:

**Comment by tolry** [comment]
Doesn't have to do anything with the metrics we discussed today, does it? Shall we move this to the far future?

**Comment by DavidBadura** [comment]
fixed with #10

**Comment by tolry** [comment]
Not really, since this issue was about integrating the tool phpmetrics and not about integrating a possibility to add metrics to a "run" :smile: But it's fine with me, since phpmetrics seems not to fit very well with our architecture and what phpmetrics delivers can now be accomplished by the features introduced by #10
