### ISSUE TITLE
[gadget] line breaks & encoding

### ISSUE THREAD

**Issue by tolry** [simpspector/analyser#16]
_From @DavidBadura on December 17, 2014 8:41_

alert if the file doesn't have unix line breaks `\n`

_Copied from original issue: simplethings/SimpSpector#83_

**Comment by tolry** [comment]
Since we are not at all judgemental, this should be configurable to reflect your favorite line break style (and default to ´\n´).

Otherwise :+1:

**Comment by DavidBadura** [comment]
maybe at least try to check utf8 encoding?

**Comment by tolry** [comment]
That would be a different gadget, wouldn't it?

**Comment by DavidBadura** [comment]
I don't know. I think we should it rename into FileGadget.

**Comment by DavidBadura** [comment]
https://github.com/squizlabs/PHP_CodeSniffer/tree/master/CodeSniffer/Standards/Generic/Sniffs/WhiteSpace
