### ISSUE TITLE
[gadget] uniform quotation

### ISSUE THREAD

**Issue by tolry** [simpspector/analyser#20]
_From @larsborn on December 8, 2014 18:59_

what do you think?

_Copied from original issue: simplethings/SimpSpector#53_

**Comment by tolry** [comment]
_From @larsborn on December 9, 2014 8:11_

this gadget should check if " and ' are both used even, when it could be avoided.

**Comment by tolry** [comment]
_From @DavidBadura on December 9, 2014 9:22_

i don't like it so much. i use the quotation marks, depending on the context and how I need it.
sometimes i need in my string `'` then i use `"` as quotation.

**Comment by tolry** [comment]
_From @larsborn on December 9, 2014 12:22_

then you should definitly disable this gadget :-p

**Comment by tolry** [comment]
I agree with @DavidBadura - there are valid use cases for both  usages. Plus, those micro optimization reasons for favoring one over the other have been proven "not relevant" by now.

**Comment by DavidBadura** [comment]
do we need this?

**Comment by tolry** [comment]
:-1:

**Comment by DavidBadura** [comment]
i close this issue. otherwise just shout ;-)
