### ISSUE TITLE
[gadget] add phpmd metrics

### ISSUE THREAD

**Issue by DavidBadura** [simpspector/analyser#28]
we have already a phpmd gadget. it create only issues and not metrics.

**Comment by tolry** [comment]
I would like to start working on this, but currently I don't see relevant metrics in the output generated. Or what would we measure here: number of rules broken grouped by type?

**Comment by DavidBadura** [comment]
phpmd is based on pdepend to create issues. but it don't display metrics so we need a new gadget named `pdepend` for metrics. #30
