### ISSUE TITLE
Optimize default command line call

### ISSUE THREAD

**Issue by dragonito** [simpspector/analyser#56]
Perhaps its good to change the default cl command to something like this:

If a `simpspector.yml` is found in the path where simpspector command is called use `./` as path and do a analyse automaticly with detail report. Instead of use of following command:

```bash
simpspector analyse ./ --format=detail
```

it would be better to call only:

```bash
simpspector
```

**Comment by DavidBadura** [comment]
if we change this, you dont see the other commands anymore.

we should keep `analyse` as argument.

```bash
simpspector analyse
```

**Comment by dragonito** [comment]
Ok sounds great :)

**Comment by tolry** [comment]
group decision: do not change format default to detail, keep the current one

addition: move formatter choice before the actual analysing is done
